[AMLCodec] Use libamcodec.so if libamplayer.so is missing
Some Linux distibutions like OpenELEC and ArchLinuxARM ship
libamcodec.so instead of libamplayer.so, which is included in the latest
buildroot package (2015-01-20-4a5990f135) from Amlogic:

  http://openlinux.amlogic.com/wiki/index.php/Arm/Buildroot
  (buildroot/package/multimedia/aml_libs/src/amcodec/Makefile, line 26)

Thus, users of these distros will eventually run into this issue:

  ERROR: Unable to load libamplayer.so, reason: libamplayer.so: cannot
  open shared object file: No such file or directory

This commit fixes that by checking if libamplayer.so can be loaded, and
if not, we'll try to use libamcodec.so instead.